name: Run CI Checks

env:
  DOCKER_BUILDKIT: 1
  BUILDX_LOCAL_CACHE_DIR: /tmp/.cache/.buildx-local-cache
  LOCAL_APP_TAG: mlinspect
  APP_NAME: mlinspect

on:
  pull_request:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-local-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up local cache for Docker layers
        uses: actions/cache@v3
        with:
          path: ${{ env.BUILDX_LOCAL_CACHE_DIR }}
          key: ${{ runner.os }}-buildx-local-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-local-
      - name: Build local image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          target: final
          tags: ${{ env.LOCAL_APP_TAG }}
          cache-from: type=local,src=${{ env.BUILDX_LOCAL_CACHE_DIR }}
          cache-to: type=local,dest=${{ env.BUILDX_LOCAL_CACHE_DIR }}-new,mode=max
      - name: Refresh local cache
        run: |
          rm -rf ${{ env.BUILDX_LOCAL_CACHE_DIR }}
          mv ${{ env.BUILDX_LOCAL_CACHE_DIR }}-new ${{ env.BUILDX_LOCAL_CACHE_DIR }}

  unit-tests:
    runs-on: ubuntu-latest
    needs: build-local-images
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up local cache for Docker layers
        uses: actions/cache@v3
        with:
          path: ${{ env.BUILDX_LOCAL_CACHE_DIR }}
          key: ${{ runner.os }}-buildx-local-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-local-
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          push: false
          load: true
          context: .
          target: final
          tags: ${{ env.LOCAL_APP_TAG }}
          cache-from: type=local,src=${{ env.BUILDX_LOCAL_CACHE_DIR }}
      - name: Run tests
        run: make test
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
